// Next Week shot list — 11 scenes / 145 shots.
// Sourced from Darion D'Anjou's shot list PDF.

export const NW_SCRIPT_URL =
  "https://drive.google.com/file/d/1anxwT68bHOqBXtb1IAjWDfeaplEaATcf/view?usp=drive_link";
export const NW_SCRIPT_LABEL = "Script · Production Final";

export const NW_PROJECT = {
  title: "Next Week",
  slug: "/nextweek",
  director: "Darion D'Anjou",
  logline:
    "A woman tests prospective partners through a holographic dating system at a refined 2035 restaurant, then meets one of them in real life.",
  primaryFrame: "9:16 vertical",
  secondaryFrame: "2.4:1 horizontal · protected",
  scriptUrl: "https://drive.google.com/file/d/1anxwT68bHOqBXtb1IAjWDfeaplEaATcf/view?usp=drive_link",
  cameraPackage: [
    { id: "FX6-A", role: "Stephanie hero CU / ECU", lenses: "85mm", note: "Protect 9:16 face composition and 2.4 shoulder width." },
    { id: "FX6-B", role: "Opposite hero CU / ECU", lenses: "85mm", note: "Covers Server, Digital Men, Bearded Man, Digital Mark, Real Mark." },
    { id: "FX3-A", role: "Wider masters, two-shots, Dana dolly", lenses: "24mm · 50mm", note: "Keeps geography and 2.4 width while preserving vertical center." },
    { id: "FX3-B", role: "Wider reverses, OTS, inserts, plates", lenses: "24mm · 50mm", note: "Useful for UI plates, entrances, profile angles, table coverage." },
  ],
};

export const NW_SCENES = [
  {
    n: 1, title: "Stephanie Day arrives at Giallo's",
    setting: "EXT/INT GIALLO'S — DAY · AMBER",
    shots: [
      { id: "1A",  type: "WS / EST",        ctx: "Giallo's is introduced as a refined 2035 restaurant. The space should feel designed, quiet, and expensive before Stephanie enters.", cam: "FX3-A", lens: "24mm",  move: "Dana dolly · slow lateral reveal", cov: "Show amber day look, restaurant geography, bar, tables, ceiling, practical atmosphere. Protect vertical center while keeping 2.4 width useful.", vfx: "ENV", seed: 0 },
      { id: "1B",  type: "WS / WALK-IN",    ctx: "Stephanie enters in her light brown day look with total control. This is her routine, not an adventure.", cam: "FX3-B", lens: "24mm",  move: "Dana dolly · push-in from entrance", cov: "Full-body walk-in. Keep posture, outfit silhouette, and Giallo's depth readable.", vfx: null, seed: 1 },
      { id: "1C",  type: "CU HERO",         ctx: "Stephanie arrives composed, sunglasses on, emotionally unreadable. Her face is the anchor for the opening mood.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for the full arrival beat. Allow subtle operator correction for head turns.", vfx: null, seed: 2 },
      { id: "1D",  type: "CU HERO",         ctx: "Server greets Stephanie like this has happened many times. She understands the pattern before Stephanie speaks.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Server hero closeup. Keep wrist cuff, hair sticks, long bangs, service uniform visible.", vfx: null, seed: 3 },
      { id: "1E",  type: "MS TRACK",        ctx: "Stephanie crosses toward her regular table. Her movement should feel precise, almost pre-programmed.", cam: "FX3-A", lens: "50mm",  move: "Dana dolly · short side track", cov: "Medium movement shot. No gimbal. Let restaurant lines and amber practicals glide behind her.", vfx: null, seed: 4 },
      { id: "1F",  type: "MWS / TABLE",     ctx: "Stephanie sits at the familiar table. The restaurant begins to respond to her presence.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Table master for Stephanie sitting and Server entering/exiting. Continuity anchor for the day setup.", vfx: null, seed: 5 },
      { id: "1G",  type: "INSERT",          ctx: "Giallo's identity needs to register early for the audience.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Clean signage or menu mark. Hold long enough for an editor to use as location punctuation.", vfx: null, seed: 0 },
      { id: "1H",  type: "ECU",             ctx: "The future restaurant reacts to Stephanie's footsteps.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Floor sensor glow under her step. Shoot practical plate and clean plate if possible.", vfx: "VFX", seed: 1 },
      { id: "1I",  type: "INSERT",          ctx: "Stephanie starts the dating ritual by placing her bag or holobud case on the table.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Hand, case, table texture, amber reflection.", vfx: null, seed: 2 },
      { id: "1J",  type: "ECU",             ctx: "The holobud case opens like a familiar habit.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Micro-tech detail. Keep movement minimal and repeatable.", vfx: "VFX?", seed: 3 },
      { id: "1K",  type: "ECU",             ctx: "Stephanie connects to the system through the microbud.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Bud entering ear. Hair, earring, skin detail, and small tech glow.", vfx: "VFX?", seed: 4 },
      { id: "1L",  type: "VFX PLATE",       ctx: "The table welcomes Stephanie back into the system.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Clean table plate for WELCOME BACK, STEPHANIE projection.", vfx: "VFX", seed: 5 },
      { id: "1M",  type: "ECU",             ctx: "A controlled smile slips through before she regains composure.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Tiny human leak. Hold after the smile fades.", vfx: null, seed: 0 },
    ],
  },
  {
    n: 2, title: "Man Search interface · Server tea beat",
    setting: "INT GIALLO'S · STEPHANIE'S TABLE — DAY",
    shots: [
      { id: "2A", type: "WMS / VFX PLATE",  ctx: "Stephanie activates Man Search. The table becomes a private dating terminal.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Table system master. Keep space for floating profiles and UI overlays.", vfx: "VFX", seed: 1 },
      { id: "2B", type: "OTS",              ctx: "Stephanie browses candidates across the empty seat, treating romance like data.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS from Stephanie toward candidate space. Holds for profile browsing.", vfx: "VFX?", seed: 2 },
      { id: "2C", type: "CU HERO",          ctx: "Stephanie evaluates the system and hides anxiety behind precision.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for full interface beat. Keep eye line consistent with UI.", vfx: null, seed: 3 },
      { id: "2D", type: "CU HERO",          ctx: "Server notices Stephanie's patterns and gently tests her denial.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Server closeup for full tea/dialogue exchange. Calm, observant, not intrusive.", vfx: null, seed: 4 },
      { id: "2E", type: "2-SHOT",           ctx: "Stephanie and Server reveal their relationship: professional, familiar, and slightly uncanny.", cam: "FX3-A", lens: "50mm",  move: "Static · loose fluid head", cov: "Two-shot table coverage. Keep both readable in vertical center and 2.4 width.", vfx: null, seed: 5 },
      { id: "2F", type: "VFX PLATE",        ctx: "The interface becomes seductive, mechanical, and ritualistic.", cam: "FX3-B", lens: "24mm",  move: "Dana dolly · slow push over table", cov: "Floating UI plate. Dolly move should feel smooth and inevitable.", vfx: "VFX", seed: 0 },
      { id: "2G", type: "ECU",              ctx: "Stephanie disables facial scan to avoid giving the system everything.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Finger on interface. Shoot clean plate and interaction pass.", vfx: "VFX", seed: 1 },
      { id: "2H", type: "ECU",              ctx: "She manually logs in, showing control and secrecy.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "User ID / password typing, reflected in glass or table if possible.", vfx: "VFX", seed: 2 },
      { id: "2I", type: "INSERT",           ctx: "Man Search loads the market of optimized romantic choices.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Floating profiles / category grid.", vfx: "VFX", seed: 3 },
      { id: "2J", type: "INSERT",           ctx: "Server places tea before Stephanie asks, proving the routine is known.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Tea landing on table. Let liquid and reflections sell the restaurant mood.", vfx: null, seed: 4 },
      { id: "2K", type: "ECU",              ctx: "Server's wrist cuff quietly confirms the restaurant is reading patterns.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Cuff glow and order history hint.", vfx: "VFX", seed: 5 },
      { id: "2L", type: "ECU",              ctx: "Stephanie's eyes shift into analysis mode.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Pupil contraction / dilation pass. Keep face still and controlled.", vfx: "VFX", seed: 0 },
    ],
  },
  {
    n: 3, title: "Digital Man #1 · Finance profile",
    setting: "INT GIALLO'S · STEPHANIE'S TABLE — DAY",
    shots: [
      { id: "3A", type: "VFX MASTER",  ctx: "Digital Man #1 appears as the polished finance candidate. He is impressive on paper before he speaks.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Master table plate. Shoot clean plate, actor pass, and empty-chair plate.", vfx: "VFX", seed: 2 },
      { id: "3B", type: "OTS",         ctx: "Stephanie tests his confidence while he treats the date like a pitch.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS Stephanie toward DM1 for the full exchange.", vfx: "VFX", seed: 3 },
      { id: "3C", type: "CU HERO",     ctx: "Stephanie studies him like a product spec and quickly sees the ego underneath.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for entire DM1 scene.", vfx: null, seed: 4 },
      { id: "3D", type: "CU HERO",     ctx: "DM1 performs status, polish, and certainty. He should feel successful but brittle.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "DM1 hero closeup for entire scene.", vfx: "VFX", seed: 5 },
      { id: "3E", type: "2-SHOT",      ctx: "The date feels transactional: charm on one side, evaluation on the other.", cam: "FX3-A", lens: "50mm",  move: "Static · loose fluid head", cov: "Two-shot across table. Needed for pop geography and eye lines.", vfx: "VFX", seed: 0 },
      { id: "3F", type: "ECU",         ctx: "DM1 becomes too pleased with himself.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Smile, eyes, teeth, polished arrogance.", vfx: "VFX", seed: 1 },
      { id: "3G", type: "INSERT",      ctx: "His profile sells finance/MBA status and high-value metrics.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Profile stats overlay beside or above him.", vfx: "VFX", seed: 2 },
      { id: "3H", type: "ECU",         ctx: "His perfect smile reads as almost artificial.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Teeth / smile detail.", vfx: "VFX", seed: 3 },
      { id: "3I", type: "ECU",         ctx: "Stephanie sees through the performance.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Analyzing eyes.", vfx: null, seed: 4 },
      { id: "3J", type: "ECU",         ctx: "Stephanie makes the rejection decision.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Finger raise before the pop.", vfx: null, seed: 5 },
      { id: "3K", type: "VFX ECU PLATE", ctx: "Her finger contacts the avatar layer.", cam: "FX6-B", lens: "85mm", move: "True locked-off ECU plate", cov: "Hologram ripple contact plate.", vfx: "VFX", seed: 0 },
      { id: "3L", type: "VFX INSERT",  ctx: "The system terminates the candidate.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "MATCH TERMINATED UI.", vfx: "VFX", seed: 1 },
      { id: "3M", type: "VFX PLATE",   ctx: "His absence should land as abruptly as a deleted file.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Empty chair after pop.", vfx: "VFX", seed: 2 },
    ],
  },
  {
    n: 4, title: "Digital Man #2 · Actor-model profile",
    setting: "INT GIALLO'S · STEPHANIE'S TABLE — DAY",
    shots: [
      { id: "4A", type: "VFX MASTER", ctx: "Digital Man #2 loads as the charming actor-model. He enters with warmth and practiced ease.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Master plate and actor pass.", vfx: "VFX", seed: 3 },
      { id: "4B", type: "OTS",        ctx: "Stephanie listens from behind her guard, intrigued despite herself.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS toward DM2 for full exchange.", vfx: "VFX", seed: 4 },
      { id: "4C", type: "CU HERO",    ctx: "Stephanie becomes briefly curious when his insecurity surfaces.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for full DM2 scene.", vfx: null, seed: 5 },
      { id: "4D", type: "CU HERO",    ctx: "DM2 performs charisma, then reveals fear of being obsolete.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "DM2 hero closeup for full scene.", vfx: "VFX", seed: 0 },
      { id: "4E", type: "2-SHOT PUSH",ctx: "The conversation almost becomes real before he retreats into performance.", cam: "FX3-A", lens: "50mm",  move: "Dana dolly · slow inward creep", cov: "Subtle push as vulnerability surfaces. Stop before it feels too romantic.", vfx: "VFX", seed: 1 },
      { id: "4F", type: "ECU",        ctx: "Charm collapses back into overcompensation.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Sincerity crack, then self-protective performance.", vfx: "VFX", seed: 2 },
      { id: "4G", type: "VFX INSERT", ctx: "The system resets from the first rejected candidate.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "NEXT CANDIDATE LOADING UI.", vfx: "VFX", seed: 3 },
      { id: "4H", type: "VFX INSERT", ctx: "DM2's data packaging sells him as attractive and emotionally compatible.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Actor-model profile stats.", vfx: "VFX", seed: 4 },
      { id: "4I", type: "ECU",        ctx: "For one beat, he feels almost human.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Vulnerable eyes.", vfx: "VFX", seed: 5 },
      { id: "4J", type: "ECU",        ctx: "Stephanie softens, then catches herself.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Listening closeup.", vfx: null, seed: 0 },
      { id: "4K", type: "ECU",        ctx: "Stephanie chooses rejection.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Finger raise / pop decision.", vfx: null, seed: 1 },
      { id: "4L", type: "VFX PLATE",  ctx: "His avatar breaks apart.", cam: "FX3-A", lens: "50mm",  move: "True locked-off plate", cov: "Hologram fragments.", vfx: "VFX", seed: 2 },
      { id: "4M", type: "VFX INSERT", ctx: "The system confirms the rejection.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "MATCH TERMINATED UI.", vfx: "VFX", seed: 3 },
    ],
  },
  {
    n: 5, title: "Server · Bearded Man interlude",
    setting: "INT GIALLO'S · BAR + STEPHANIE'S TABLE",
    shots: [
      { id: "5A", type: "WS / TRACK",     ctx: "Bearded Man watches from the bar and gathers courage. Unlike the holograms, he has to physically cross the room.", cam: "FX3-A", lens: "24mm",  move: "Dana dolly · slow bar-to-table", cov: "Connects his human presence to Stephanie spatially.", vfx: null, seed: 4 },
      { id: "5B", type: "MS",             ctx: "Server returns with lemons and reads the room before anyone explains it.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Medium table angle with Stephanie and Server.", vfx: null, seed: 5 },
      { id: "5C", type: "CU HERO",        ctx: "Stephanie remains hard to impress, but the interruption cracks her perfect rhythm.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for whole interlude.", vfx: null, seed: 0 },
      { id: "5D", type: "CU HERO",        ctx: "Bearded Man tries real-world charm. He is funny, warm, and slightly nervous.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Bearded Man hero closeup for whole exchange.", vfx: null, seed: 1 },
      { id: "5E", type: "3-SHOT",         ctx: "Human chaos enters Stephanie's perfect system.", cam: "FX3-A", lens: "50mm",  move: "Static · loose fluid head", cov: "Three-person table coverage with Server reaction when useful.", vfx: null, seed: 2 },
      { id: "5F", type: "OTS / PHYSICAL", ctx: "Stephanie tests whether he can be dismissed like a hologram.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS / physical interaction coverage for the poke and aftermath.", vfx: null, seed: 3 },
      { id: "5G", type: "INSERT",         ctx: "Server's lemon ritual punctures the tension with ordinary restaurant life.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Lemons placed down.", vfx: null, seed: 4 },
      { id: "5H", type: "ECU",            ctx: "Bearded Man steels himself before approaching.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Adjusting shirt / nervous confidence.", vfx: null, seed: 5 },
      { id: "5I", type: "INSERT",         ctx: "A small human comedy beat before the approach.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Beer bottle or breath-check detail, tasteful and quick.", vfx: null, seed: 0 },
      { id: "5J", type: "ECU",            ctx: "Stephanie experiences a tiny authentic smile.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "First real spark of amusement.", vfx: null, seed: 1 },
      { id: "5K", type: "VFX INSERT",     ctx: "The system cannot classify him because he is outside her search flow.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "NO DATA / no profile overlay.", vfx: "VFX", seed: 2 },
      { id: "5L", type: "ECU",            ctx: "Stephanie pokes him instead of swiping him away.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Physical contact test.", vfx: null, seed: 3 },
      { id: "5M", type: "CU",             ctx: "He does not disappear. The moment embarrasses both of them.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Bearded Man reaction, wounded but dignified.", vfx: null, seed: 4 },
    ],
  },
  {
    n: 6, title: "Digital Man #3 · Doctor profile",
    setting: "INT GIALLO'S · STEPHANIE'S TABLE — DAY",
    shots: [
      { id: "6A", type: "VFX MASTER", ctx: "Doctor avatar appears as the safest candidate: stable, calm, medically trustworthy.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Master plate and actor pass.", vfx: "VFX", seed: 5 },
      { id: "6B", type: "OTS",        ctx: "Stephanie interrogates his empathy and family-values script.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS toward Doctor for full test conversation.", vfx: "VFX", seed: 0 },
      { id: "6C", type: "CU HERO",    ctx: "Stephanie detects that his warmth is calculated instead of felt.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for whole Doctor scene.", vfx: null, seed: 1 },
      { id: "6D", type: "CU HERO",    ctx: "Doctor gives comforting answers that become too optimized under pressure.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Doctor hero closeup for whole scene.", vfx: "VFX", seed: 2 },
      { id: "6E", type: "2-SHOT PUSH",ctx: "His empathy test becomes a trap closing around the algorithm.", cam: "FX3-A", lens: "50mm",  move: "Dana dolly · tiny push-in", cov: "Subtle pressure move as his answers start lagging.", vfx: "VFX", seed: 3 },
      { id: "6F", type: "MS",         ctx: "Server sees the pattern repeat and confirms this is not the first failed cycle.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Server return after Doctor pop.", vfx: null, seed: 4 },
      { id: "6G", type: "VFX INSERT", ctx: "The safe choice loads with medical authority.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Doctor profile UI.", vfx: "VFX", seed: 5 },
      { id: "6H", type: "ECU",        ctx: "His response engine delays under emotional ambiguity.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Rendering delay / eye flicker.", vfx: "VFX", seed: 0 },
      { id: "6I", type: "ECU",        ctx: "Stephanie catches the flaw.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Pupil shift / detection.", vfx: "VFX", seed: 1 },
      { id: "6J", type: "ECU",        ctx: "Stephanie rejects the safest option.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Finger raise.", vfx: null, seed: 2 },
      { id: "6K", type: "VFX PLATE",  ctx: "The Doctor avatar is terminated.", cam: "FX3-A", lens: "50mm",  move: "True locked-off plate", cov: "Doctor pop / fragments.", vfx: "VFX", seed: 3 },
      { id: "6L", type: "ECU",        ctx: "Stephanie disconnects briefly from the system.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Earbud local mode shift.", vfx: "VFX", seed: 4 },
      { id: "6M", type: "ECU",        ctx: "She returns to the system because the pattern is stronger than the discomfort.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Earbud digital mode shift.", vfx: "VFX", seed: 5 },
    ],
  },
  {
    n: 7, title: "Digital Mark · optimized profile avatar",
    setting: "INT GIALLO'S · STEPHANIE'S TABLE — DAY",
    shots: [
      { id: "7A", type: "VFX MASTER", ctx: "Digital Mark appears as the best match: the optimized version of what Stephanie thinks she wants.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Table master / Digital Mark VFX plate.", vfx: "VFX", seed: 1 },
      { id: "7B", type: "OTS",        ctx: "Stephanie evaluates him more seriously because the system finally feels close.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS toward Digital Mark for the whole exchange.", vfx: "VFX", seed: 2 },
      { id: "7C", type: "CU HERO",    ctx: "Stephanie feels attraction and suspicion at the same time.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for full Digital Mark scene.", vfx: "VFX", seed: 3 },
      { id: "7D", type: "CU HERO",    ctx: "Digital Mark is calm, lean, attractive, and grounded — engineered to feel authentic.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Digital Mark hero closeup for full scene.", vfx: "VFX", seed: 4 },
      { id: "7E", type: "2-SHOT PUSH",ctx: "The conversation feels closest to real intimacy, even though it is still mediated by the system.", cam: "FX3-A", lens: "50mm",  move: "Dana dolly · slow push toward two-shot", cov: "Romantic pull-in. Keep Digital Mark and Stephanie clean for comp.", vfx: "VFX", seed: 5 },
      { id: "7F", type: "MS / UI",    ctx: "Stephanie decides to schedule real-world verification.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Interface / two-shot support.", vfx: "VFX", seed: 0 },
      { id: "7G", type: "VFX INSERT", ctx: "The system presents Digital Mark as the chosen match.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "Digital Mark profile card.", vfx: "VFX", seed: 1 },
      { id: "7H", type: "ECU",        ctx: "His eye contact is stable in a way the others were not.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Digital Mark eyes / controlled presence.", vfx: "VFX", seed: 2 },
      { id: "7I", type: "ECU",        ctx: "Stephanie registers attraction, then scans for defects.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Pupils dilate then narrow.", vfx: "VFX", seed: 3 },
      { id: "7J", type: "ECU",        ctx: "She chooses the next step.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Schedule verification tap.", vfx: "VFX", seed: 4 },
      { id: "7K", type: "VFX INSERT", ctx: "The plot turns from simulation to real-world meeting.", cam: "FX3-B", lens: "50mm",  move: "True locked-off plate", cov: "MEETING CONFIRMED / NEXT WEEK UI.", vfx: "VFX", seed: 5 },
      { id: "7L", type: "VFX PLATE",  ctx: "Digital Mark disappears, leaving the chair empty and Stephanie alone again.", cam: "FX3-A", lens: "50mm",  move: "True locked-off plate", cov: "Digital Mark dissolves.", vfx: "VFX", seed: 0 },
      { id: "7M", type: "CU",         ctx: "Stephanie watches empty air too long. The choice has emotional weight.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Loneliness after the choice.", vfx: "VFX", seed: 1 },
    ],
  },
  {
    n: 8, title: "One week later · Stephanie Night waits · Real Mark enters",
    setting: "INT GIALLO'S — NIGHT · CYAN + AMBER",
    shots: [
      { id: "8A", type: "WS / EST",      ctx: "Giallo's shifts to night. Same location, but now the emotional stakes are real.", cam: "FX3-A", lens: "24mm",  move: "Dana dolly · slow reveal", cov: "Night restaurant master with cyan/amber mix.", vfx: "ENV", seed: 2 },
      { id: "8B", type: "MS",            ctx: "Stephanie waits in her black dress, trying to appear present and calm.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Table medium / waiting composition.", vfx: null, seed: 3 },
      { id: "8C", type: "CU HERO",       ctx: "Stephanie anticipates the real date and hides vulnerability behind poise.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie Night hero closeup.", vfx: null, seed: 4 },
      { id: "8D", type: "CU HERO",       ctx: "Real Mark enters nervous, human, and visibly unlike the optimized avatar.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Real Mark hero closeup from entrance through sitting.", vfx: null, seed: 5 },
      { id: "8E", type: "WS / WALK-IN",  ctx: "Real Mark crosses the restaurant toward the woman who expected the avatar version of him.", cam: "FX3-A", lens: "24mm",  move: "Dana dolly · short push from entrance", cov: "Controlled arrival. No gimbal drift.", vfx: null, seed: 0 },
      { id: "8F", type: "MS",            ctx: "Server resets the familiar ritual with tea, now in a more emotionally exposed context.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Tea drop-off / table continuity.", vfx: null, seed: 1 },
      { id: "8G", type: "INSERT",        ctx: "The empty opposite chair creates anticipation before Mark arrives.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Chair and place setting.", vfx: null, seed: 2 },
      { id: "8H", type: "ECU",           ctx: "Real Mark freezes when he sees Stephanie.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Vulnerable first reaction.", vfx: null, seed: 3 },
      { id: "8I", type: "ECU",           ctx: "Stephanie scans the mismatch between Digital Mark and Real Mark.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Eyes and micro-expression.", vfx: null, seed: 4 },
      { id: "8J", type: "ECU",           ctx: "Mark's hands betray his anxiety.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Nervous hands, glass, table edge.", vfx: null, seed: 5 },
      { id: "8K", type: "INSERT",        ctx: "Tea lands between them like a repeated ritual from the first date.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Tea placed between Stephanie and Mark.", vfx: null, seed: 0 },
    ],
  },
  {
    n: 9, title: "Real Mark date · main conversation",
    setting: "INT GIALLO'S — NIGHT · TWO-TOP",
    shots: [
      { id: "9A", type: "WS / TABLE",     ctx: "Real Mark and Stephanie sit with emotional distance between them. This setup holds the whole conversation geography.", cam: "FX3-A", lens: "24mm",  move: "Static · loose fluid head", cov: "Full table master for entire date.", vfx: null, seed: 1 },
      { id: "9B", type: "PROFILE 2-SHOT", ctx: "The conversation slowly becomes intimate as silence starts to matter.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Profile two-shot for full date.", vfx: null, seed: 2 },
      { id: "9C", type: "CU HERO",        ctx: "Stephanie fights programming while trying to stay composed.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup for entire date scene.", vfx: null, seed: 3 },
      { id: "9D", type: "CU HERO",        ctx: "Mark reveals sincerity, fear, and hope. His imperfection is the point.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Real Mark hero closeup for entire date scene.", vfx: null, seed: 4 },
      { id: "9E", type: "OTS",            ctx: "Mark tries to connect directly, not as a profile or avatar.", cam: "FX3-A", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS Stephanie toward Mark.", vfx: null, seed: 5 },
      { id: "9F", type: "OTS",            ctx: "Stephanie answers from behind the mask, then slowly lets the mask slip.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "OTS Mark toward Stephanie.", vfx: null, seed: 0 },
      { id: "9G", type: "2-SHOT PUSH",    ctx: "The date pulls them closer emotionally during the strongest stretch of truth-telling.", cam: "FX3-A", lens: "50mm",  move: "Dana dolly · very slow creep-in", cov: "Use once for the emotional center. Do not overuse movement.", vfx: null, seed: 1 },
      { id: "9H", type: "ECU PASS",       ctx: "Stephanie glitches when real choice conflicts with system logic.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Stephanie ECU pass for yes / no, pupils, blink.", vfx: "VFX", seed: 2 },
      { id: "9I", type: "ECU PASS",       ctx: "Mark's hope becomes visible because he is being seen instead of filtered.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Mark ECU pass for vulnerability.", vfx: null, seed: 3 },
      { id: "9J", type: "INSERT",         ctx: "Stephanie controls emotion through small physical gestures.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Teacup hand / controlled fingers.", vfx: null, seed: 4 },
      { id: "9K", type: "INSERT",         ctx: "Mark's anxiety shows in his hands before it shows in words.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Fidgeting hands.", vfx: null, seed: 5 },
      { id: "9L", type: "ECU",            ctx: "Real connection registers inside Stephanie.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Pupil dilation.", vfx: "VFX", seed: 0 },
      { id: "9M", type: "ECU",            ctx: "Stephanie says yes too fast, revealing the programmed answer.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Fast response closeup.", vfx: null, seed: 1 },
      { id: "9N", type: "ECU",            ctx: "Stephanie says no before correcting herself, exposing the system breach.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Hard NO moment.", vfx: null, seed: 2 },
      { id: "9O", type: "ECU",            ctx: "The correction happens in the blink.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Blink recalibration.", vfx: "VFX", seed: 3 },
      { id: "9P", type: "ECU",            ctx: "Mark listens instead of performing. This separates him from the holograms.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Quiet listening closeup.", vfx: null, seed: 4 },
    ],
  },
  {
    n: 10, title: "Touch · goodbye · hand kiss",
    setting: "INT GIALLO'S — NIGHT · TABLE → EXIT",
    shots: [
      { id: "10A", type: "WS / TABLE",   ctx: "Mark asks for another real meeting. The scene moves from evaluation into invitation.", cam: "FX3-A", lens: "24mm",  move: "Static · loose fluid head", cov: "Wider table coverage.", vfx: null, seed: 5 },
      { id: "10B", type: "SIDE 2-SHOT",  ctx: "The physical distance finally closes.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Side two-shot for hands and goodbye.", vfx: null, seed: 0 },
      { id: "10C", type: "CU HERO",      ctx: "Stephanie lets herself feel something without fully understanding it.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Stephanie hero closeup through touch / goodbye.", vfx: null, seed: 1 },
      { id: "10D", type: "CU HERO",      ctx: "Mark feels hope and relief, but he leaves without forcing the moment.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Mark hero closeup through hand kiss / exit.", vfx: null, seed: 2 },
      { id: "10E", type: "WS / EXIT",    ctx: "Mark leaves and Stephanie remains changed in the same seat where the system started.", cam: "FX3-A", lens: "24mm",  move: "Dana dolly · slow retreat or lateral reveal", cov: "Mark exit / Stephanie isolation.", vfx: null, seed: 3 },
      { id: "10F", type: "ECU",          ctx: "Mark reaches across the table with a real invitation.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Hand reaching.", vfx: null, seed: 4 },
      { id: "10G", type: "ECU",          ctx: "Stephanie hesitates before accepting touch.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Hand hesitation.", vfx: null, seed: 5 },
      { id: "10H", type: "ECU",          ctx: "Their hands meet, creating the first truly human contact beat.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Hands meet. Consider matching FX6-B angle if time allows.", vfx: null, seed: 0 },
      { id: "10I", type: "ECU",          ctx: "Mark kisses her hand with old-school tenderness.", cam: "FX6-B", lens: "85mm", move: "Static · loose head ECU", cov: "Hand kiss.", vfx: null, seed: 1 },
      { id: "10J", type: "ECU",          ctx: "Stephanie reacts with genuine warmth instead of programmed polish.", cam: "FX6-A", lens: "85mm", move: "Static · loose head ECU", cov: "Human reaction.", vfx: null, seed: 2 },
      { id: "10K", type: "INSERT",       ctx: "The door closes and leaves Stephanie with the choice.", cam: "FX3-B", lens: "50mm",  move: "Static · loose fluid head", cov: "Door closing.", vfx: null, seed: 3 },
      { id: "10L", type: "CU",           ctx: "Stephanie stares at the door after Mark leaves.", cam: "FX6-A", lens: "85mm",  move: "Static · loose fluid head", cov: "Emotional residue.", vfx: null, seed: 4 },
    ],
  },
  {
    n: 11, title: "Simulation reveal",
    setting: "INT GIALLO'S → SYSTEM SPACE",
    shots: [
      { id: "11A", type: "VFX MASTER", ctx: "The restaurant drains into reveal mode. The romantic scene becomes a system evaluation.", cam: "FX3-A", lens: "24mm",  move: "True locked-off plate", cov: "Restaurant master and clean plate.", vfx: "VFX", seed: 0 },
      { id: "11B", type: "VFX PLATE",  ctx: "Server returns as witness, suggesting the loop may continue.", cam: "FX6-B", lens: "85mm",  move: "Static · loose fluid head", cov: "Server final approach / system-space plate.", vfx: "VFX", seed: 1 },
    ],
  },
];

// Production reset — nothing shot yet.
export const NW_DEFAULT_DONE = new Set();
export const NW_ACTIVE_ID = null;
